spring:
  application:
    name: eureka-server
server:
  port: 1000

eureka:
  server:
    enable-self-preservation: true #自我保护模式,默认打开
    eviction-interval-timer-in-ms: 60000 #每隔20秒执行一次清理注册（默认为1分钟）

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka2:1100/eureka/
---
spring:
  profiles: p1100
server:
  port: 1100
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:1000/eureka/